# Orders service configuration

# Database configuration
database:
  host: "db"
  port: 5432
  username: "postgres"
  password: "password"
  name: "postgres"
  schema: "public"

# gRPC Server configuration
grpc:
  host: "0.0.0.0"
  port: 3081

# HTTP Server configuration
http:
  host: "0.0.0.0"
  port: 3082
